.base:
  variables:
    APCI_ALPAKA_ROOT: "$CI_PROJECT_DIR"
    APCI_RUN_CTEST: "ON"
    APCI_EXEC_CPU_SERIAL: "OFF"
    APCI_HIP : 0
    APCI_ONEAPI : 0
    APCI_ONEAPI_TARGET: none
  script:
    - $APCI_ALPAKA_ROOT/script/ci/job_info.sh
    - $APCI_ALPAKA_ROOT/script/ci/install_dependencies.sh
    - $APCI_ALPAKA_ROOT/script/ci/configure.sh
    - $APCI_ALPAKA_ROOT/script/ci/build.sh
    - $APCI_ALPAKA_ROOT/script/ci/test.sh
  interruptible: true
  tags:
  - x86_64
  - cpuonly

.hip:
  extends: .base
  tags:
    - x86_64
    - rocm

gcc-13:
  image: docker.io/ubuntu:24.04
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : gcc@13
    APCI_CMAKE: 3.28.3
    APCI_EXEC_CPU_SERIAL: "ON"

gcc-15:
  image: docker.io/ubuntu:24.04
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : gcc@15
    APCI_CMAKE: 3.28.3
    APCI_EXEC_CPU_SERIAL: "ON"

gcc-12-agc:
  image: registry.hzdr.de/crp/alpaka-group-container/alpaka-ci-ubuntu24.04-gcc:4.0
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : gcc@12
    APCI_CMAKE: 3.31.4
    APCI_EXEC_CPU_SERIAL: "ON"

clang-19:
  image: docker.io/ubuntu:24.04
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : clang@19
    APCI_CMAKE: 3.28.3
    APCI_EXEC_CPU_SERIAL: "ON"

clang-21:
  image: docker.io/ubuntu:24.04
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : clang@21
    APCI_CMAKE: 3.28.3
    APCI_EXEC_CPU_SERIAL: "ON"

clang-20-agc:
  image: registry.hzdr.de/crp/alpaka-group-container/alpaka-ci-ubuntu24.04-gcc:4.0
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : clang@20
    APCI_CMAKE: 3.31.4
    APCI_EXEC_CPU_SERIAL: "ON"

hipcc-6.2-agc:
  image: registry.hzdr.de/crp/alpaka-group-container/alpaka-ci-ubuntu22.04-rocm6.2:4.0
  extends: .hip
  variables:
    APCI_DEVICE_COMPILER : clang@18
    APCI_CMAKE: 3.31.4
    APCI_HIP : 6.2

hipcc-6.3-rocm-container:
  image: rocm/dev-ubuntu-24.04:6.3.4
  extends: .hip
  variables:
    APCI_DEVICE_COMPILER : clang@18
    APCI_CMAKE: 3.28.3
    APCI_HIP : 6.3

hipcc-6.4:
  image: docker.io/ubuntu:24.04
  extends: .hip
  variables:
    APCI_DEVICE_COMPILER : clang@21
    APCI_CMAKE: 3.28.3
    APCI_HIP : 6.4.2

hipcc-7.0:
  image: ubuntu:24.04
  extends: .hip
  variables:
    APCI_DEVICE_COMPILER : clang@20
    APCI_CMAKE: 3.31.4
    APCI_HIP : 7.0

hipcc-7.1:
  image: docker.io/ubuntu:24.04
  extends: .hip
  variables:
    APCI_DEVICE_COMPILER : clang@20
    APCI_CMAKE: 3.28.3
    APCI_HIP : 7.1

hipcc-7.2-rocm-container:
  image: rocm/dev-ubuntu-24.04:7.2
  extends: .hip
  variables:
    APCI_DEVICE_COMPILER : clang@22
    APCI_CMAKE: 3.28.3
    APCI_HIP : 7.2

icpx-2025.1-cpu:
   image: docker.io/ubuntu:24.04
   extends: .base
   variables:
    APCI_DEVICE_COMPILER : icpx@2025.1
    APCI_CMAKE: 3.28.3
    APCI_ONEAPI: 2025.1
    APCI_ONEAPI_TARGET: cpu

icpx-2025.1-gpu:
   image: docker.io/ubuntu:24.04
   extends: .base
   variables:
    APCI_DEVICE_COMPILER : icpx@2025.1
    APCI_CMAKE: 3.28.3
    APCI_ONEAPI: 2025.1
    APCI_ONEAPI_TARGET: intel_gpu
    APCI_RUN_CTEST: "OFF"

icpx-2025.2-cpu:
   image: docker.io/ubuntu:24.04
   extends: .base
   variables:
    APCI_DEVICE_COMPILER : icpx@2025.2
    APCI_CMAKE: 3.28.3
    APCI_ONEAPI: 2025.2
    APCI_ONEAPI_TARGET: cpu

icpx-2025.2-gpu:
   image: docker.io/ubuntu:24.04
   extends: .base
   variables:
    APCI_DEVICE_COMPILER : icpx@2025.2
    APCI_CMAKE: 3.28.3
    APCI_ONEAPI: 2025.2
    APCI_ONEAPI_TARGET: intel_gpu
    APCI_RUN_CTEST: "OFF"

icpx-2025.3-cpu:
   image: docker.io/ubuntu:24.04
   extends: .base
   variables:
    APCI_DEVICE_COMPILER : icpx@2025.3
    APCI_CMAKE: 3.28.3
    APCI_ONEAPI: 2025.3
    APCI_ONEAPI_TARGET: cpu

icpx-2025.3-gpu:
   image: docker.io/ubuntu:24.04
   extends: .base
   variables:
    APCI_DEVICE_COMPILER : icpx@2025.3
    APCI_CMAKE: 3.28.3
    APCI_ONEAPI: 2025.3
    APCI_ONEAPI_TARGET: intel_gpu
    APCI_RUN_CTEST: "OFF"

icpx-2026.0-cpu:
   image: docker.io/ubuntu:24.04
   extends: .base
   variables:
    APCI_DEVICE_COMPILER : icpx@2026.0
    APCI_CMAKE: 3.28.3
    APCI_ONEAPI: 2026.0
    APCI_ONEAPI_TARGET: cpu

icpx-2026.0-gpu:
   image: docker.io/ubuntu:24.04
   extends: .base
   variables:
    APCI_DEVICE_COMPILER : icpx@2026.0
    APCI_CMAKE: 3.28.3
    APCI_ONEAPI: 2026.0
    APCI_ONEAPI_TARGET: intel_gpu
    APCI_RUN_CTEST: "OFF"

icpx-2026.0-cpu-intel-container:
   image: docker.io/intel/oneapi:2026.0.0-devel-ubuntu24.04
   extends: .base
   variables:
    APCI_DEVICE_COMPILER : icpx@2026.0
    APCI_CMAKE: 3.28.3
    APCI_ONEAPI: 2026.0
    APCI_ONEAPI_TARGET: cpu

icpx-2026.0-gpu-intel-container:
   image: docker.io/intel/oneapi:2026.0.0-devel-ubuntu24.04
   extends: .base
   variables:
    APCI_DEVICE_COMPILER : icpx@2026.0
    APCI_CMAKE: 3.28.3
    APCI_ONEAPI: 2026.0
    APCI_ONEAPI_TARGET: intel_gpu
    APCI_RUN_CTEST: "OFF"
