name: CI Build and Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

env:
  alpaka_cmake_flags: "-Dalpaka_TESTING=ON -Dalpaka_BENCHMARKS=ON -Dalpaka_EXAMPLES=ON -DBUILD_TESTING=ON -Dalpaka_HEADERCHECKS=ON"

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          clangFormatVersion: 16
          inplace: True
      - run: |
          git diff --exit-code > format.patch
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: format.patch
          path: format.patch

  ci:
    # Default runner for non-CUDA/HIP tests; overridden for CUDA/HIP
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { compiler: gcc, version: "12", cuda: "no", hip: "no", container: "ubuntu:24.04" }
          - { compiler: gcc, version: "13", cuda: "no", hip: "no", container: "ubuntu:24.04" }
          - { compiler: gcc, version: "14", cuda: "no", hip: "no", container: "ubuntu:24.04" }
          - { compiler: clang, version: "17", cuda: "no", hip: "no", container: "ubuntu:24.04" }
          - { compiler: clang, version: "18", cuda: "no", hip: "no", container: "ubuntu:24.04" }
          - { compiler: clang, version: "19", cuda: "no", hip: "no", container: "ubuntu:24.04" }
          - { compiler: nvcc, version: "", cuda: "12.5", hip: "no", container: "nvidia/cuda:12.5.1-devel-ubuntu24.04" }
          - { compiler: nvcc, version: "", cuda: "12.6", hip: "no", container: "nvidia/cuda:12.6.3-devel-ubuntu24.04" }
          - { compiler: nvcc, version: "", cuda: "12.8", hip: "no", container: "nvidia/cuda:12.8.0-devel-ubuntu24.04" }
          - { compiler: clang, version: "18", cuda: "no", hip: "6.2.4", container: "rocm/dev-ubuntu-24.04:6.2.4" }
          - { compiler: clang, version: "18", cuda: "no", hip: "6.3.4", container: "rocm/dev-ubuntu-24.04:6.3.4" }
          - { compiler: icpx, version: "2025.1", cuda: "no", hip: "no", container: "intel/oneapi-hpckit:2025.1.0-0-devel-ubuntu24.04" }
      fail-fast: false

    # Specify the container to use based on the matrix configuration
    container:
      image: ${{ matrix.config.container }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install base dependencies
      - name: Install base dependencies
        run: |
          apt-get update
          apt-get install -y cmake build-essential ninja-build git

      # Install GCC if specified
      - name: Install GCC
        if: matrix.config.compiler == 'gcc'
        run: |
          apt-get update
          apt-get install -y gcc-${{ matrix.config.version }} g++-${{ matrix.config.version }}
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.config.version }} 100 \
                              --slave /usr/bin/g++ g++ /usr/bin/g++-${{ matrix.config.version }}

      # Install Clang if specified
      - name: Install Clang
        if: matrix.config.compiler == 'clang' && matrix.config.hip == 'no'
        run: |
          apt-get update
          apt-get install -y clang-${{ matrix.config.version }}
          update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${{ matrix.config.version }} 100 \
                              --slave /usr/bin/clang++ clang++ /usr/bin/clang++-${{ matrix.config.version }}
          apt install -y libomp-${{ matrix.config.version }}-dev

      # ROCm
      - name: Install ROCm
        if: matrix.config.hip != 'no'
        run: |
          apt-get update
          apt-get install -y hiprand-dev rocrand-dev

          export ROCM_PATH=/opt/rocm
          export CMAKE_PREFIX_PATH=$ROCM_PATH:$CMAKE_PREFIX_PATH
          export HIP_PLATFORM="amd"
          export HIP_DEVICE_LIB_PATH=${ROCM_PATH}/amdgcn/bitcode
          export HSA_PATH=$ROCM_PATH
          export PATH=${ROCM_PATH}/bin:$PATH
          export PATH=${ROCM_PATH}/llvm/bin:$PATH

          # Export variables to make them globally visible
          echo "ROCM_PATH=${ROCM_PATH}" >> $GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}" >> $GITHUB_ENV
          echo "HIP_PLATFORM=${HIP_PLATFORM}" >> $GITHUB_ENV
          echo "HSA_PATH=${HSA_PATH}" >> $GITHUB_ENV
          echo "PATH=${PATH}" >> $GITHUB_ENV

          which clang++
          clang++ --version
          hipconfig --platform
          hipconfig -v

      # intel oneAPI ipcx
      - name: Install oneAPI
        if: matrix.config.compiler == 'icpx'
        run: |
          echo "use icpx"

      # Configure CMake with the selected compiler and options
      - name: Configure CMake
        run: |
          mkdir build && cd build
          if [ "${{ matrix.config.compiler }}" = "gcc" ]; then
            export CC=gcc-${{ matrix.config.version }}
            export CXX=g++-${{ matrix.config.version }}
          elif [ "${{ matrix.config.compiler }}" = "clang" ]; then
            export CC=clang
            export CXX=clang++
          fi
          cmake -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                ${alpaka_cmake_flags} -Dalpaka_DEP_OMP=ON \
                ${{ matrix.config.compiler == 'icpx' && '-DCMAKE_CXX_COMPILER=icpx -Dalpaka_DEP_ONEAPI_CPU=ON -Dalpaka_EXEC_CpuSerial=OFF -Dalpaka_DEP_OMP=OFF' || '' }} \
                ${{ matrix.config.cuda != 'no' && '-Dalpaka_DEP_CUDA=ON' || '' }} \
                ${{ matrix.config.hip != 'no' && '-DCMAKE_CXX_COMPILER=clang++ -Dalpaka_DEP_HIP=ON -Dalpaka_DEP_OMP=OFF \
                   -DCMAKE_HIP_ARCHITECTURES=gfx906 -DAMDGPU_TARGETS=gfx906' || '' }} ..

      # Build the project
      - name: Build
        run: |
          cd build
          pwd
          ninja

      # Run tests (assuming your project has tests)
      - name: Run Tests
        if: matrix.config.cuda == 'no' && matrix.config.hip == 'no'
        run: |
          cd build
          ctest --output-on-failure
